services:
  cast-operations-docker-agent:
    image: cast-operations/docker-agent:release
    container_name: cast-operations-docker-agent
    user: "0:0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - CAST_OPERATIONS_URL=${CAST_OPERATIONS_URL}
      - CAST_OPERATIONS_SERVICE_TOKEN=${CAST_OPERATIONS_SERVICE_TOKEN}
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME:-docker-host}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
